#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"


source "$(dirname "${BASH_SOURCE[0]}")/../../lib/shared.sh"

echo "*** simple plugin *** ${BUILDKITE_PLUGIN_SIMPLE_NAME}"